### ISSUE TITLE
it asks me to UNINSTALL grub-efi-amd64

### ISSUE THREAD

**Issue by binpda45** [slacka/WinUSB#36]
the program asks to uninstall grub-efi-amd64 so if i install this, will my  system be bootable?

**Comment by Lin-Buo-Ren** [comment]
Hi, if you mean APT/DPKG request to uninstall grub-efi-amd64 it might be an issue of the package dependencies (debian/control).

Is your system using 32bit UEFI or 64bit?  Tell us your hardware manufacturer & model.

Curently the debian control file request the system to install grub-pc OR grub-efi package and grub-efi currently seems to depend on grub-efi-amd64, this might be the problem for 32bit UEFI users.

**Comment by Lin-Buo-Ren** [comment]
It seems that your condition is rather different as I initially expected, as the package requested your to uninstall grub-efi-amd64 it seems that it is trying to install the grub-pc package, which conflicts with grub-efi-* packages, this shouldn't be happening at all because since [https://github.com/slacka/WinUSB/commit/adca402456182ae467ea08d198f3a74a58b3651b](v1.0.11) the debian control file is already updated to depend either grub-pc OR grub-efi.

What WinUSB version are you using?  Have you tried the latest revision on the master branch?

**Comment by binpda45** [comment]
i have uninstalled it but when i try to install it again, it asks me to
 install grub-pc-bin  and wants to uninstall grub-efi-amd64. my system is
kubuntu 16.04 64 bits and kde is my DE. here is a screenshot.   my language
is turkish.

2016-07-08 20:43 GMT+03:00 林博仁(Buo-Ren Lin) <notifications@github.com>:

**Comment by Lin-Buo-Ren** [comment]
Unable to reproduce this issue, please try the latest development snapshot and report a new one if you still have problem installing WinUSB

**Comment by Lin-Buo-Ren** [comment]
The runtime dependency has been improved to avoid depending on the actual bootloader packages since commit 1d56809a, please do comment if you still encounter this issue.
